coverage:
  precision: 2
  round: down
  status:
    project:
      default: true
      src:
        target: 0.4
        threshold: 0.1
        paths:
          - src

ignore:
  docs/*
  cmake/*
  test/*
