name: kvtree build and test

permissions:
  actions: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        target: [Debug, Release]
        mpi: [seq, par]

    name: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.mpi }}

    runs-on: $${{ matrix.os }}

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: kvtree
          fetch-depth: 0

      - name: get deps
        uses: ecp-veloc/github-actions/get-scr-os-deps
        with:
          os: ${{ matrix.os }}
          mpi: $${{ matrix.mpi }}

      - name: configure
        run: |
          mkdir build
          cd build
          cmake ../kvtree

      - name: build
        run: |
          cd build
          make

      - name: check
        run: |
          cd build
          make check
